'use strict';

/**
 * 1206 F2 — the Guard speaks the canonical v2 request.
 *
 * The parity anchor is `coderifts-app/test/fixtures/v2-grant-canonical-request.json`: one full
 * authorize request with every declared field, plus the NORMALIZED READING the app's handler
 * produces from it. Four speakers can serialise the same bytes and still disagree about what
 * they mean — that an absent tenant_id is the literal `default`, that an absent
 * expected_state_token is `''` rather than unbound. Byte-equivalence alone is not parity.
 *
 * NON-SILENT SKIP. Without the app checkout this test SKIPS with a named reason, never passes
 * quietly: a green suite that proved nothing about parity is the failure this file exists to
 * prevent.
 */

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

// V2_WIRE_FIELDS is module-local (not on the package entry) — read it where it lives.
const { V2_WIRE_FIELDS } = require('../dist/cjs/execution-grant.js');

function fixturePath() {
  for (const root of [
    process.env.CODERIFTS_APP_ROOT,
    path.join(process.env.HOME || '', 'coderifts-app'),
    path.join(__dirname, '..', '..', 'coderifts-app'),
  ]) {
    const p = root && path.join(root, 'test', 'fixtures', 'v2-grant-canonical-request.json');
    if (p && fs.existsSync(p)) return p;
  }
  return null;
}

// 1394 — this was the last honest SKIP in a clean room, and it guards exactly what 1402 fixed:
// which fields the Guard puts on the wire vs which the handler reads. A skipped parity test is how
// that drifted in the first place, so it now runs RECORDED against the pinned fixture instead.
const rec = require('../lib/recorded-app-sync');
const LIVE_FIXTURE = fixturePath();
const LIVE = !!LIVE_FIXTURE;
const MODE = LIVE ? 'LIVE' : 'RECORDED';
const FIXTURE_PATH = LIVE_FIXTURE || rec.snapshotPath('v2-grant-canonical-request.json');

describe(`canonical v2 request parity (Guard) ${rec.modeBanner(MODE)}`, () => {
  const fixture = JSON.parse(fs.readFileSync(FIXTURE_PATH, 'utf8'));
  const { request, reading } = fixture;

  it('the fixture is the generated one, not a copy someone edited', () => {
    assert.equal(fixture.schema, 'coderifts.v2-grant-canonical-request.v1');
    assert.match(fixture.$comment, /GENERATED by scripts\/generate-grant-request-types\.js/);
  });

  it('EVERY V2 wire field the Guard sends appears in the canonical request', () => {
    // V2_WIRE_FIELDS is [wireName, configName]. The wire half is what reaches the server.
    for (const [wire] of V2_WIRE_FIELDS) {
      // audience_hash is DERIVED server-side from `audience` and is not a request field
      // (app schemas/execution-grant-request.v2.producer.json). The Guard still sends it;
      // that it has no effect is the documented state, and it is asserted below.
      if (wire === 'audience_hash') continue;
      assert.ok(
        Object.prototype.hasOwnProperty.call(request, wire),
        `the Guard sends ${wire} but the canonical request does not declare it`,
      );
    }
  });

  it('BYTE-EQUIVALENCE: a Guard-shaped body serialises to the fixture bytes on the wire fields', () => {
    // Build the request the way guard.ts does: the v2 selector + the wire fields it configures.
    const guardBody = { include_execution_grant: true, grant_version: 'v2' };
    for (const [wire] of V2_WIRE_FIELDS) {
      if (wire === 'audience_hash') continue;
      if (Object.prototype.hasOwnProperty.call(request, wire)) guardBody[wire] = request[wire];
    }
    for (const k of Object.keys(guardBody)) {
      assert.equal(
        JSON.stringify(guardBody[k]), JSON.stringify(request[k]),
        `${k} does not serialise byte-equivalently to the canonical request`,
      );
    }
  });

  it('AGREEMENT WITH THE READING: what the Guard sends is what the handler reads', () => {
    // The half that byte-equivalence cannot cover.
    assert.equal(request.tenant_id, reading.tenant_id);
    assert.equal(request.executor_id, reading.executor_id);
    assert.equal(request.adapter_id, reading.adapter_id);
    assert.equal(request.target_uri, reading.target_uri);
    assert.equal(request.expected_state_token, reading.expected_state_token);
    assert.equal(request.policy_hash, reading.policy_hash);
    // state_nonce is SENT under that name and READ as `nonce` — a rename across the boundary
    // that a byte comparison would never surface.
    assert.equal(request.state_nonce, reading.nonce);
    // operation lives on context on the way in and is read flat.
    assert.equal(request.context.operation, reading.operation);
  });

  it('the RECORDED fixture is not stale (LIVE only)', { skip: LIVE ? false : 'RECORDED mode — nothing live to compare against' }, () => {
    // A snapshot nobody re-checks rots into a second truth. Checked only where a live copy exists.
    const snap = rec.snapshotBytes('v2-grant-canonical-request.json');
    assert.ok(snap.equals(fs.readFileSync(LIVE_FIXTURE)),
      'RECORDED v2-grant-canonical-request.json is STALE vs the app — regenerate fixtures/recorded/app-sync');
  });

  it('1402: the Guard no longer sends the inert audience_hash', () => {
    // THIS TEST INVERTED. It used to assert "the Guard does send it" beside "the handler does not
    // read it" — a correct measurement of a real bug, pinned but not fixed. The handler reads
    // top-level `audience` (change-set.js:1138) and derives the hash itself
    // (execution-grant-v2.js:166); the request schema says so outright. So the Guard sending
    // audience_hash bound nothing, and it is gone.
    const sends = V2_WIRE_FIELDS.map(([w]) => w);
    assert.equal(sends.includes('audience_hash'), false, 'an inert field must not be re-added');
    assert.equal('audience_hash' in reading, false, 'the handler still does not read it');
  });
});
